drop table if exists CUSTOMER; 
create table CUSTOMER(
	CUSTOMER_NUM varchar(10), 
	NAME varchar(255),
	ACTIVE varchar(1),
	REGISTRATION_DT date,
	PRIMARY KEY (CUSTOMER_NUM)
	);
	
drop table if exists CONTACT; 
create table CONTACT(
	ID number(5),
	FIRSTNAME varchar(255),
	LASTNAME varchar(255),
	MALE varchar(1),
	PRIMARY KEY (ID)
	);

drop table if exists CUSTOMER_CONTACT; 
create table CUSTOMER_CONTACT(
	CONTACT_ID number(5),
	CUSTOMER_NUM varchar(10),
	PRIMARY KEY (CONTACT_ID, CUSTOMER_NUM),
	CONSTRAINT FK_CONTACT_ON_CUSTOMER_CONTACT FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT(ID),
	CONSTRAINT FK_CUSTOMER_ON_CUSTOMER_CONTACT FOREIGN KEY (CUSTOMER_NUM) REFERENCES CUSTOMER(CUSTOMER_NUM)
	);

drop table if exists ADDRESS; 
create table ADDRESS(
	ID number(5),
	STREET varchar(255),
	ZIP_CODE varchar(6),
	CITY varchar(255),
	COUNTRY varchar(255),
	CONTACT_ID number(5),
	PRIMARY KEY (ID),
	CONSTRAINT FK_CONTACT_ON_ADDRESS FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT(ID)
	);

drop table if exists PRODUCT; 
create table PRODUCT(
	SERIAL_NUM varchar(32),
	PRODUCT_TYPE varchar(1),
	PRICE number(6),
	CUSTOMER_NUM varchar(10),
	PRIMARY KEY (SERIAL_NUM),
	CONSTRAINT FK_CUSTOMER_ON_PRODUCT FOREIGN KEY (CUSTOMER_NUM) REFERENCES CUSTOMER(CUSTOMER_NUM)
	);
